### ISSUE TITLE
Runtime issues

### ISSUE THREAD

**Issue by makdoudN** [mpSchrader/gym-sokoban#12]
Hi,

Thank you for open source this awesome project!

Is there a mechanism for avoiding runtime issue like:

```python
env = gym.make('TinyWorld-Sokoban-small-v0')  # Error
# RuntimeError: Not enough free spots (#3) to place 1 player and 2 boxes.
```

There is also possible issue when we reset the environment
```python
env = gym.make('TinyWorld-Sokoban-small-v0')
for _ in range(int(1e3)):
    env.reset()
# RuntimeError: Not enough free spots (#3) to place 1 player and 2 boxes.
# or
# RuntimeWarning: Generated Model with score == 0 
```

A simple workaround for the issue with reset could be:

```python

def callback_sokoban_reset(f):
    def callback():
        try:
            return f()
        except (RuntimeWarning, RuntimeError):
            print("[SOKOBAN] Runtime error retry . . .")
            return callback()
    return callback

env = gym.make('TinyWorld-Sokoban-small-v0')
env.reset = callback_sokoban_reset(env.reset)

```
but there is maybe a more efficient way of dealing with these issues.

**Comment by mpSchrader** [comment]
Hi,

Thank you for your feedback! 

I think this error occurs, when there are not enough free spaces in the room. See [room_utils.py at line 143](https://github.com/mpSchrader/gym-sokoban/blob/master/gym_sokoban/envs/room_utils.py#L143). One way to get rid of this problem might be to add a constraint in the [room_topology_generation](https://github.com/mpSchrader/gym-sokoban/blob/master/gym_sokoban/envs/room_utils.py#L52) function, which requires enough free spaces during the random walk. 

During the weekend I will fix this issue or if you want you can also fix the issue.

**Comment by mpSchrader** [comment]
Regarding the score == 0 warning, you need to adjust the [number of tries](https://github.com/mpSchrader/gym-sokoban/blob/master/gym_sokoban/envs/room_utils.py#L8) to generate a valid room. We cloud change it to infinit tries, if this makes sense.

**Comment by makdoudN** [comment]
Thank you for the quick answer.

Is there any reason not to make `tries` arbitrarily large?

**Comment by mpSchrader** [comment]
Hey @makdoudN I fixed the issue by adding a recursive call to the reset function, which is some adoption of your callback suggestion. 

I did not made the number of tries not arbitrary, because I thought it might result in some runtime issues. After I made some tests today it does not seem to be an issue. So I used your input to fix it!
