### ISSUE TITLE
Reward calculation

### ISSUE THREAD

**Issue by Olloxan** [mpSchrader/gym-sokoban#14]
Hi,
function _calc_reward() in sokoban_env.py is only called, when action is < 4. So if i start training and actions are >= 4 the penalty for steps is 0 until the chosen action is < 4 for the first time. I don´t know if this has any effect in the longrun (e.g. if rewards are calculated correctly in general)

**Comment by mpSchrader** [comment]
Hi @Olloxan,
thank you very much for the issue. I will check it later today and let you know,

**Comment by mpSchrader** [comment]
Hi Olloxan,
you were right the reward calculation has been called on the wrong level. I just moved the _calc_reward() behind the if-else-block, such that it will be called every step.
