### ISSUE TITLE
check, if game is done

### ISSUE THREAD

**Issue by Olloxan** [mpSchrader/gym-sokoban#15]
Hi, 
could it be that in file sokoban_env.py function "_check_if_done()" is not considering self.max_steps in evaluation, if a game is done?

**Comment by mpSchrader** [comment]
Hi,
yes you are correct, I missed to add to the return as an or-condition.
Thank you for the feedback, looks like you are the doing some good stress testing! ;-)

**Comment by Olloxan** [comment]
yes, I am basically wondering why I don´t get any rewards in my simulation and work my way through the code. But thanks for providing the environment. I had to search quite some time to find this solution. Good work!

**Comment by mpSchrader** [comment]
Thank you for your feedback! It is great to see other people using the repo for something cool!

By the way if you find such simple bug. Feel free to just fix them and  create a pull request!

**Comment by Olloxan** [comment]
ok, I will, thanks

**Comment by mpSchrader** [comment]
Also it would great if you could let me know, what kind of improvements could be done regarding the documentation.
