### ISSUE TITLE
action env.step(action) returns done=True even when the target is not reached

### ISSUE THREAD

**Issue by Rajshreed** [mpSchrader/gym-sokoban#19]
Hi, in the Sokoban code, I tried running the code for max steps 150, but I see that the env files have max_steps default to 120 and the done is set to True even when target is not reached.

Is there a way I can define the max_steps to higher value in env? Is there any function or value to be set?

**Comment by mpSchrader** [comment]
Hi @Rajshreed,
the environment returns True either when all boxes are push on the targets or when you reached the maximum number of steps.

Regarding your question on how to change the max_steps, now there are two possibilities to change them.
1. Change the max_steps in your local [sokoban_env_variations.py](https://github.com/mpSchrader/gym-sokoban/blob/master/gym_sokoban/envs/sokoban_env_variations.py) file.
2. Second after creating the environment you can run `env.unwrapped.set_maxsteps(200)`. This will change the maximum number of steps only for the specific instance.

I hope this helps. If so please close the issue and feel free to star the repo!

Best,
Max

**Comment by mpSchrader** [comment]
P.s: Please pull the latest version of the repo, because I did some change. ;-)
________________________________

**Comment by Rajshreed** [comment]
Thanks Max for responding and providing the solution.

But there still is one problem, I think we need to have pull action as well, i see most of the time the boxes are stuck in position from which they can never be pulled and hence how ever my max_steps be it still will never reach the target!

**Comment by mpSchrader** [comment]
Hi,

Regarding the pull actions. They are not part of the classical game, which makes the game a very difficult game for RL algorithms due to irreversible mistakes.

I am planing to create a variation which allows push and pull actions.

Best,
Max
________________________________
