### ISSUE TITLE
what is successful rate for generating environment?,in Sokoban-v1

### ISSUE THREAD

**Issue by wrongbattery** [mpSchrader/gym-sokoban#26]
Sometime this warning "[SOKOBAN] Runtime Error/Warning: Generated Model with score == 0
[SOKOBAN] Retry . . ." happens. This effects the speed of game.

**Comment by mpSchrader** [comment]
I am planning to work on this upcoming Wednesday.

**Comment by mpSchrader** [comment]
Hey,
something came up at work and it will take a few more days until I will be able to work on it.
I already compared the algorithm briefly with the one proposed by DeepMind. It looks like all the numbers are all the same. 
As I already said. I might tweak the algorithm to generate a new every time.

**Comment by wrongbattery** [comment]
Ok.thanks for your information


Vào 15:46, T.3, 4 Th12, 2018 Max Schrader <notifications@github.com đã viết:

**Comment by mpSchrader** [comment]
Hey @wrongbattery,
I am currently still really busy at work and writing my thesis. 
Regarding the success rate. Do you want to write a small script calculating the success rate and commit it to the repo?

Regarding changing the algorithm for the generation. I think it would not make that much sense to change it. The only thing I could think about is to not limit the number of tries to generate a feasible room and instead just the environment retry until it succeeds.
What do you think? Would this help you?

**Comment by mpSchrader** [comment]
@wrongbattery I just integrated DeepMinds pregenerated levels, which can now be used as environments ([Readme](https://github.com/mpSchrader/gym-sokoban/blob/master/docs/variations/Boxoban.md)). This solves the problem regarding the level generation.
I will close the issue. If you have any other questions, let me know.

**Comment by wrongbattery** [comment]
Thank you so much for your information

Vào 17:58, T.3, 28 Th5, 2019 Max Schrader <notifications@github.com> đã
viết:
