### ISSUE TITLE
cannot re-register id

### ISSUE THREAD

**Issue by Mephisto632** [mpSchrader/gym-sokoban#29]
If I try to run a script twice which imports "gym_sokoban", I get the error "cannot re-register id: Sokoban-v0"

I have to restart my kernel to be able to run it again. 

Any suggestions?

**Comment by mpSchrader** [comment]
Hi,
Just to clarify. Your code looks something like this:
```python 
import gym_sokoban
from importlib import reload
reload(gym_sokoban) # Here occurs the error
``` 
You can unregister all Sokoban environments by calling like explained in https://github.com/openai/gym/issues/1172
```python
for env in gym.envs.registry.env_specs:
     if 'Sokoban' in env:
          print('Remove {} from registry".format(env))
          del gym.registry.env_specs[env]
```
This would work, but out of curiosity, why do you need to import the environment twice?

Best,
Max

**Comment by mpSchrader** [comment]
If you want to add this to this repository, feel free to add it to the registering code. See:
https://github.com/mpSchrader/gym-sokoban/blob/master/gym_sokoban/__init__.py

**Comment by Mephisto632** [comment]
At the moment my code is:
`import gym
import gym_sokoban

env = gym.make('Sokoban-v0')
env.reset()`

When I run this immediately after opening Spyder, it runs fine. If I try to run it again, I get the  "cannot re-register id: Sokoban-v0" error. This makes it impossible to write a program without restarting the kernel every time.

Best,
Pierre

**Comment by mpSchrader** [comment]
Oh I see. This is probably, because Spyder reloads the imported modules. Did you try the following:
```python
import gym
for env in gym.envs.registry.env_specs:
     if 'Sokoban' in env:
          print('Remove {} from registry".format(env))
          del gym.registry.env_specs[env]
import gym_sokoban

env = gym.make('Sokoban-v0')
env.reset()
```
This should be a quick fix for your problem.

**Comment by mpSchrader** [comment]
@Mephisto632 Did this fix solved your problem? :-)

**Comment by mpSchrader** [comment]
Closing issue. If you still have troubles, reopen the issue.

**Comment by makeller1** [comment]
I ran into this same issue when trying to implement a custom gym environment to be used with off-the-shelf reinforcement learning libraries (like spinningup).

@mpSchrader solution worked for me with some slight adjustments:

`import gym
env_dict = gym.envs.registration.registry.env_specs.copy()
for env in env_dict:
     if 'Sokoban' in env:
          print('Remove {} from registry'.format(env))
          del gym.envs.registration.registry.env_specs[env]
import gym_sokoban

env = gym.make('Sokoban-v0')
env.reset()`

**Comment by rhalbersma** [comment]
Shouldn't this type of guard reside in the `__init__.py` where the registration occurs?

**Comment by mpSchrader** [comment]
Hi @rhalbersma,
Thanks for your input. Yes, that would be a good idea. Currently I am swamped with other projects. 
It would be great, if you have the time to author a short PR to handle this within the package itself.
Best,
Max
