### ISSUE TITLE
Add NOOP action

### ISSUE THREAD

**Issue by mjanschek** [mpSchrader/gym-sokoban#37]
As for many gym environments, action 0 should map to NOOP (no operation = no movement for a step of the environment).
Some common environment wrapper and agents utilize this option, especially the paper deepmind released the boxoban-levels for:
[https://deepmind.com/research/publications/investigation-model-free-planning/](paper)

**Comment by mjanschek** [comment]
Just wanted to add that i am really glad you did this implementation, even more with the recent boxoban-addon.

**Comment by mpSchrader** [comment]
Thank you very much for your feedback. I am currently in the final phase of my thesis, so it might take some time till I can work on your two issues. In case you have some spare time, feel free to work on the two issues.

**Comment by mpSchrader** [comment]
I will have some spare time on Wednesday and could work on the NOOP action. Before I do so, I just wanted to check whether you already started working on the issue.

**Comment by mjanschek** [comment]
Not started yet, thanks for asking :-)
While doing so, could you reduce the boxoban-verbosity further? I only removed level-printing, but the level loading still adds up during training sessions.
Maybe make it optional

**Comment by mpSchrader** [comment]
Just implemented NOOP action for all envs.
