### ISSUE TITLE
pip installation not working

### ISSUE THREAD

**Issue by mjanschek** [mpSchrader/gym-sokoban#44]
Python can't import the pip installation

> ModuleNotFoundError: No module named 'gym_sokoban'

maybe a typo?

**Comment by mpSchrader** [comment]
Let me check it, after work to night.


Best,
Max

________________________________

**Comment by mpSchrader** [comment]
It wasn't a typo on your side. The problem has been an incomplete setup.py, which I didn't recognize because I tried pip install on my laptop. 
```bash
pip install gym-sokoban==0.0.5
```
Now everything should work, so I will close this issue. If you still experience trouble, please let me know.
