### ISSUE TITLE
How to use the game?

### ISSUE THREAD

**Issue by N-Kingsley** [mpSchrader/gym-sokoban#46]
Hi,  I used "gym.make(Sokoban)" to create the environment, but there was an error that "No registered env with id: Sokoban-v0". How to deal with it?

**Comment by mpSchrader** [comment]
Hi,
Did you import both Python packages(gym and gym_sokoban)?
Also have a look at the examples and the readme:
- https://github.com/mpSchrader/gym-sokoban/blob/master/examples/readme.md
- https://github.com/mpSchrader/gym-sokoban/tree/master/examples

Please let me know if that helped you.

________________________________
Von: N-Kingsley <notifications@github.com>
Gesendet: Donnerstag, 14. November 2019, 7:17 vorm.
An: mpSchrader/gym-sokoban
Cc: Subscribed
Betreff: [mpSchrader/gym-sokoban] How to use the game? (#46)


Hi, I used "gym.make(Sokoban)" to create the environment, but there was an error that "No registered env with id: Sokoban-v0". How to deal with it?

**Comment by N-Kingsley** [comment]
Thank you very much, the problem has been solved when I import gym_sokoban.
